processed 13 tasks

task 6 'run'. lines 16-36:
{
  "gas_used": 741952,
  "status": "Executed"
}

task 7 'run'. lines 39-47:
{
  "gas_used": 24935,
  "status": "Executed"
}

task 8 'run'. lines 49-62:
{
  "gas_used": 151442,
  "status": "Executed"
}

task 9 'run'. lines 64-103:
{
  "gas_used": 723904,
  "status": "Executed"
}

task 10 'run'. lines 105-124:
{
  "gas_used": 210047,
  "status": "Executed"
}

task 12 'run'. lines 128-152:
{
  "gas_used": 213991,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwapRouter"
        }
      },
      "abort_code": "1006"
    }
  }
}
