[package]
name = "Starswap-Core"
version = "2.0.6"

[addresses]
StarcoinFramework = "0x1"
SwapAdmin = "0x9ea0286f273deb7450f97756769f3e82"
SwapFeeAdmin = "0xa040a4cc626966ab0cd42163ebc0bf91"
BuyBackAccount = "0x6b4c03242bfb61d4bc11bb409d825ddb"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "198d236f071819257ebdf54ed4502099a7daaaf5" }
Mock-Token = {local = "./MockToken"}