[package]
name = "Starswap-Core"
version = "2.1.0"

[addresses]
StarcoinFramework = "0x1"
SwapAdmin = "0xb9bad301cc50cb623efac44b81f7289b"
SwapFeeAdmin = "0x25ea0e4f37f497b0359aa467c98ce014"
BuyBackAccount = "0xe058652cad0a9fc58591b3ee72452038"

[dependencies.StarcoinFramework]
git = "https://github.com/starcoinorg/starcoin-framework.git"
rev = "198d236f071819257ebdf54ed4502099a7daaaf5"

[dependencies.Mock-Token]
local = "./MockToken"
