[package]
name = "Starswap-Core"
version = "2.1.0"

[addresses]
StarcoinFramework = "0x1"
SwapAdmin = "0xa13791083ac4b77d7eb5470590797620"
SwapFeeAdmin = "0x3682c783869dbbfa3edc446c33fe71f4"
BuyBackAccount = "0xaa5baa28af206d6fdf487cb7391b4a5f"

[dependencies.StarcoinFramework]
git = "https://github.com/starcoinorg/starcoin-framework.git"
rev = "198d236f071819257ebdf54ed4502099a7daaaf5"

[dependencies.Mock-Token]
local = "./MockToken"
