processed 12 tasks

task 4 'run'. lines 9-21:
{
  "gas_used": 2779773,
  "status": "Executed"
}

task 5 'run'. lines 23-32:
{
  "gas_used": 34291,
  "status": "Executed"
}

task 6 'run'. lines 35-68:
{
  "gas_used": 525406,
  "status": "Executed"
}

task 7 'run'. lines 70-84:
{
  "gas_used": 1047668,
  "status": "Executed"
}

task 8 'run'. lines 86-107:
{
  "gas_used": 92788,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwapSyrup"
        }
      },
      "abort_code": "26625"
    }
  }
}

task 10 'run'. lines 111-139:
{
  "gas_used": 978623,
  "status": "Executed"
}

task 11 'run'. lines 141-172:
{
  "gas_used": 841888,
  "status": "Executed"
}
