processed 16 tasks

task 4 'run'. lines 9-21:
{
  "gas_used": 2981689,
  "status": "Executed"
}

task 5 'run'. lines 23-32:
{
  "gas_used": 34047,
  "status": "Executed"
}

task 6 'run'. lines 35-68:
{
  "gas_used": 546937,
  "status": "Executed"
}

task 7 'run'. lines 70-84:
{
  "gas_used": 859203,
  "status": "Executed"
}

task 8 'run'. lines 86-107:
{
  "gas_used": 72906,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwapSyrup"
        }
      },
      "abort_code": "26625"
    }
  }
}

task 10 'run'. lines 111-139:
{
  "gas_used": 726451,
  "status": "Executed"
}

task 11 'run'. lines 141-172:
{
  "gas_used": 648451,
  "status": "Executed"
}

task 12 'run'. lines 174-183:
{
  "gas_used": 214973,
  "status": "Executed"
}

task 13 'run'. lines 185-199:
{
  "gas_used": 378040,
  "status": "Executed"
}

task 14 'run'. lines 202-228:
{
  "gas_used": 160955,
  "status": "Executed"
}

task 15 'run'. lines 230-249:
{
  "gas_used": 240633,
  "status": "Executed"
}
