processed 8 tasks

task 4 'run'. lines 22-62:
{
  "gas_used": 1548078,
  "status": "Executed"
}

task 5 'run'. lines 63-76:
{
  "gas_used": 562118,
  "status": "Executed"
}

task 6 'run'. lines 79-112:
warning[W09001]: unused alias
   ┌─ TEMPFILE3:84:30
   │
84 │     use starcoin_std::debug::print;
   │                              ^^^^^ Unused 'use' of alias 'print'. Consider removing it

{
  "gas_used": 1894457,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwap"
        }
      },
      "function": 11,
      "code_offset": 41
    }
  }
}

task 7 'run'. lines 115-136:
{
  "gas_used": 27215,
  "status": "Executed"
}
