processed 8 tasks

task 4 'run'. lines 22-61:
{
  "gas_used": 1548078,
  "status": "Executed"
}

task 5 'run'. lines 63-76:
{
  "gas_used": 562118,
  "status": "Executed"
}

task 6 'run'. lines 79-108:
{
  "gas_used": 1875676,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwap"
        }
      },
      "function": 11,
      "code_offset": 41
    }
  }
}

task 7 'run'. lines 111-132:
{
  "gas_used": 27215,
  "status": "Executed"
}
