processed 10 tasks

task 3 'run'. lines 7-16:
{
  "gas_used": 132082,
  "status": "Executed"
}

task 4 'run'. lines 18-31:
{
  "gas_used": 149736,
  "status": "Executed"
}

task 5 'run'. lines 33-44:
{
  "gas_used": 457535,
  "status": "Executed"
}

task 6 'run'. lines 46-61:
{
  "gas_used": 608743,
  "status": "Executed"
}

task 7 'run'. lines 62-75:
{
  "gas_used": 767836,
  "status": "Executed"
}

task 8 'run'. lines 76-90:
{
  "gas_used": 282650,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwap"
        }
      },
      "abort_code": "2010"
    }
  }
}

task 9 'run'. lines 91-102:
{
  "gas_used": 767836,
  "status": "Executed"
}
