processed 18 tasks

task 6 'run'. lines 15-27:
{
  "gas_used": 503764,
  "status": "Executed"
}

task 7 'run'. lines 30-43:
{
  "gas_used": 514738,
  "status": "Executed"
}

task 8 'run'. lines 45-53:
{
  "gas_used": 117453,
  "status": "Executed"
}

task 9 'run'. lines 56-71:
{
  "gas_used": 195061,
  "status": "Executed"
}

task 10 'run'. lines 73-83:
{
  "gas_used": 34047,
  "status": "Executed"
}

task 11 'run'. lines 85-95:
{
  "gas_used": 33852,
  "status": "Executed"
}

task 12 'run'. lines 98-108:
{
  "gas_used": 104465,
  "status": "Executed"
}

task 13 'run'. lines 111-137:
{
  "gas_used": 2690707,
  "status": "Executed"
}

task 14 'run'. lines 140-157:
{
  "gas_used": 3126812,
  "status": "Executed"
}

task 15 'run'. lines 160-174:
{
  "gas_used": 269878,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwap"
        }
      },
      "function": 9,
      "code_offset": 1
    }
  }
}

task 16 'run'. lines 177-211:
{
  "gas_used": 2837638,
  "status": "Executed"
}

task 17 'run'. lines 214-249:
{
  "gas_used": 2758449,
  "status": "Executed"
}
