processed 12 tasks

task 6 'run'. lines 15-25:
{
  "gas_used": 132082,
  "status": "Executed"
}

task 7 'run'. lines 28-42:
{
  "gas_used": 146427,
  "status": "Executed"
}

task 8 'run'. lines 44-56:
{
  "gas_used": 465483,
  "status": "Executed"
}

task 9 'run'. lines 59-83:
{
  "gas_used": 386640,
  "status": "Executed"
}

task 10 'run'. lines 85-110:
{
  "gas_used": 167618,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "TokenSwap"
        }
      },
      "abort_code": "2010"
    }
  }
}

task 11 'run'. lines 112-135:
{
  "gas_used": 397957,
  "status": "Executed"
}
