processed 18 tasks

task 5 'run'. lines 13-20:
{
  "gas_used": 132082,
  "status": "Executed"
}

task 6 'run'. lines 22-32:
{
  "gas_used": 146363,
  "status": "Executed"
}

task 7 'run'. lines 34-43:
{
  "gas_used": 410980,
  "status": "Executed"
}

task 8 'run'. lines 45-57:
{
  "gas_used": 415376,
  "status": "Executed"
}

task 9 'run'. lines 59-68:
{
  "gas_used": 80301,
  "status": "Executed"
}

task 10 'run'. lines 70-81:
{
  "gas_used": 76625,
  "status": "Executed"
}

task 11 'run'. lines 82-100:
{
  "gas_used": 329296,
  "status": "Executed"
}

task 12 'run'. lines 102-120:
{
  "gas_used": 75675,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "SwapLiquidityProvider"
        }
      },
      "abort_code": "20004"
    }
  }
}

task 13 'run'. lines 122-138:
{
  "gas_used": 68635,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "SwapLiquidityProvider"
        }
      },
      "abort_code": "20004"
    }
  }
}

task 14 'run'. lines 140-158:
{
  "gas_used": 68716,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "SwapLiquidityProvider"
        }
      },
      "abort_code": "20002"
    }
  }
}

task 15 'run'. lines 160-175:
{
  "gas_used": 68716,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "SwapLiquidityProvider"
        }
      },
      "abort_code": "20002"
    }
  }
}

task 16 'run'. lines 177-191:
{
  "gas_used": 57246,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x8c109349c6bd91411d6bc962e080c4a3",
          "name": "SwapLiquidityProvider"
        }
      },
      "abort_code": "20001"
    }
  }
}

task 17 'run'. lines 193-228:
{
  "gas_used": 455959,
  "status": "Executed"
}
