processed 23 tasks

task 6 'run'. lines 15-27:
{
  "gas_used": 381084,
  "status": {
    "Keep": "Executed"
  }
}

task 7 'run'. lines 29-41:
{
  "gas_used": 392251,
  "status": {
    "Keep": "Executed"
  }
}

task 8 'run'. lines 44-52:
{
  "gas_used": 117449,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 55-69:
{
  "gas_used": 27790,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Token"
          }
        },
        25858
      ]
    }
  }
}

task 10 'run'. lines 72-83:
{
  "gas_used": 34291,
  "status": {
    "Keep": "Executed"
  }
}

task 11 'run'. lines 86-96:
{
  "gas_used": 34084,
  "status": {
    "Keep": "Executed"
  }
}

task 12 'run'. lines 99-110:
{
  "gas_used": 34084,
  "status": {
    "Keep": "Executed"
  }
}

task 13 'run'. lines 113-125:
{
  "gas_used": 106064,
  "status": {
    "Keep": "Executed"
  }
}

task 14 'run'. lines 128-140:
{
  "gas_used": 14549,
  "status": {
    "Keep": {
      "ExecutionFailure": {
        "location": {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Account"
          }
        },
        "function": 54,
        "code_offset": 4
      }
    }
  }
}

task 15 'run'. lines 143-164:
{
  "gas_used": 1657268,
  "status": {
    "Keep": "Executed"
  }
}

task 16 'run'. lines 168-176:
{
  "gas_used": 87342,
  "status": {
    "Keep": "Executed"
  }
}

task 17 'run'. lines 179-196:
{
  "gas_used": 1485860,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Token"
          }
        },
        26120
      ]
    }
  }
}

task 18 'run'. lines 199-237:
{
  "gas_used": 182918,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwapLibrary"
          }
        },
        1001
      ]
    }
  }
}

task 19 'run'. lines 240-285:
{
  "gas_used": 109174,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwapLibrary"
          }
        },
        1001
      ]
    }
  }
}

task 20 'run'. lines 289-330:
{
  "gas_used": 110312,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwapLibrary"
          }
        },
        1001
      ]
    }
  }
}

task 21 'run'. lines 333-367:
{
  "gas_used": 185918,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwapLibrary"
          }
        },
        1001
      ]
    }
  }
}

task 22 'run'. lines 370-401:
{
  "gas_used": 88365,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwapLibrary"
          }
        },
        1001
      ]
    }
  }
}
