processed 18 tasks

task 6 'run'. lines 14-26:
{
  "gas_used": 504960,
  "status": {
    "Keep": "Executed"
  }
}

task 7 'run'. lines 29-42:
{
  "gas_used": 517722,
  "status": {
    "Keep": "Executed"
  }
}

task 8 'run'. lines 45-53:
{
  "gas_used": 37887,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 56-71:
{
  "gas_used": 195679,
  "status": {
    "Keep": "Executed"
  }
}

task 10 'run'. lines 73-83:
{
  "gas_used": 34291,
  "status": {
    "Keep": "Executed"
  }
}

task 11 'run'. lines 85-95:
{
  "gas_used": 34084,
  "status": {
    "Keep": "Executed"
  }
}

task 12 'run'. lines 97-108:
{
  "gas_used": 104953,
  "status": {
    "Keep": "Executed"
  }
}

task 13 'run'. lines 110-136:
{
  "gas_used": 2699829,
  "status": {
    "Keep": "Executed"
  }
}

task 14 'run'. lines 139-156:
{
  "gas_used": 3142966,
  "status": {
    "Keep": "Executed"
  }
}

task 15 'run'. lines 159-173:
{
  "gas_used": 274705,
  "status": {
    "Keep": {
      "ExecutionFailure": {
        "location": {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwap"
          }
        },
        "function": 9,
        "code_offset": 1
      }
    }
  }
}

task 16 'run'. lines 176-215:
{
  "gas_used": 4254120,
  "status": {
    "Keep": "Executed"
  }
}

task 17 'run'. lines 218-255:
{
  "gas_used": 4090047,
  "status": {
    "Keep": "Executed"
  }
}
