processed 11 tasks

task 4 'run'. lines 9-18:
{
  "gas_used": 34291,
  "status": {
    "Keep": "Executed"
  }
}

task 5 'run'. lines 20-59:
{
  "gas_used": 1004352,
  "status": {
    "Keep": "Executed"
  }
}

task 6 'run'. lines 61-75:
{
  "gas_used": 876919,
  "status": {
    "Keep": "Executed"
  }
}

task 7 'run'. lines 77-98:
{
  "gas_used": 98964,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x8c109349c6bd91411d6bc962e080c4a3",
            "name": "TokenSwapSyrup"
          }
        },
        26625
      ]
    }
  }
}

task 9 'run'. lines 102-130:
{
  "gas_used": 822513,
  "status": {
    "Keep": "Executed"
  }
}

task 10 'run'. lines 132-163:
{
  "gas_used": 909294,
  "status": {
    "Keep": "Executed"
  }
}
